name: chatbot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  speech_to_text: ^7.0.0
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.5
  flutter_tts: ^4.0.2
  google_generative_ai: ^0.4.6
  permission_handler: ^11.3.1  # Agrega esta línea
  intl: ^0.17.0                # Agrega esta línea
  shared_preferences: ^2.0.9    # Agrega esta línea

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
